modLoader="javafml"
loaderVersion="[43,)"
license="MIT License"
[[mods]]
modId="slabstoblocks_createdeco"
version="${file.jarVersion}"
displayName="Slabs to Blocks: Create Deco"
logoFile="SlabstoBlocks_CreateDeco_Icon.png"
credits="Idea for this mod was from the original Slabs to Blocks by Mars"
authors="LneedhelpnowPLS"
description='''
Adds crafting recipes for Create Deco's slab related things, examples being:
Crafting horizontal slabs back into blocks,
Crafting vertical slabs back into blocks,
Crafting vertical slabs straight from the blocks,
And converting vertical slabs into horizontal slabs.
'''
[[dependencies.slabstoblocks_createdeco]]
modId="forge"
mandatory=true
versionRange="[43,)"
ordering="NONE"
side="BOTH"
[[dependencies.slabstoblocks_createdeco]]
modId="minecraft"
mandatory=true
versionRange="[1.19.2,1.20)"
ordering="NONE"
side="BOTH"